from typing import Any, Mapping

class Response:
    status_code: int
    def raise_for_status(self) -> None: ...
    def json(self) -> Mapping[str, Any]: ...

def get(url: str, *args: Any, **kwargs: Any) -> Response: ...

class RequestException(Exception): ...
